# Generated by Django 3.2.2 on 2021-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.EmailField(max_length=256)),
                ('fullname', models.CharField(max_length=256)),
            ],
        ),
    ]
